services:
  leap:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: leap
    command:
      - --genesis-json
      - /opt/leap/config/genesis.json
      # - --snapshot
      # - /opt/leap/snapshots/snapshot-225128604.bin
      - --disable-replay-opts
    ulimits:
      nproc: 1048576
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - ./xpr-mainnet/config:/opt/leap/config
      - ./xpr-mainnet/data:/opt/leap/data
      # - ./xpr-mainnet/snapshots:/opt/leap/snapshots
    ports:
      - "8888:8888"
      - "8080:8080"